name: Embedding-SwinV2-Base-CXL-Open
model_wandb_url: "/workspaces/gorillatracker/trained_models/Embedding-SwinV2-Base-CXL-Open/xm6o9trh/checkpoints/last_model_ckpt.ckpt"

save_quantized_model: False
load_quantized_model: False
save_model_architecture: False
base_dir: "/workspaces/gorillatracker/runs/"
input_height: 192

number_of_calibration_images: 100

dataset_path: "/workspaces/gorillatracker/data/supervised/splits/cxl_faces_openset_seed42_square_kfold-5"